const message = {
    LOGIN_SUCCESS: "Logged in Successfully !!",
    INVALID_TOKEN: "Your token has been expired, Please login again !!",
    EMAIL_NOT_MATCH: "This email address does not exists !!",
    PASSWORD_NOT_MATCH: "Password did not match !!",
    USER_NOT_FOUND: "User not found !!",
    DATA_NOT_FOUND: "Data not found !!",
    USER_NOT_REGISTERED: "User does not registered!!",
    USER_REGISTRATION: "User Registration successfully",
    ADMIN_REGISTRATION: "Admin Registration successfully",
    EMAIL_ALREADY_EXISTS: "Email already exists please enter another email!",
    EMAIL_NOT_MATCH: "This email address does not exists!",
    VERIFY_SUCCESS:"successfully verify!",
    ADMIN_DATA_DELETED:"Admin data deleted successfully ",
    ERROR_MESSAGE: "Unexpected error occurred!",
    ADMIN_DATA_UPDATE:"Data updated successfully",
    ADMIN_FILE_UPDATE_SUCCESS:"Admin profile update successfully",
    ADMIN_FILE_UPDATE_FAILED:"Admin profile update failed !!",
    ADMIN_DATA_UPDATE:"Data updated successfully",
    USER_FILE_UPDATE_SUCCESS:"User profile image update successfully",
    USER_FILE_UPDATE_FAILED:"User profile image update failed !!",
    PRODUCT_ADD_SUCCESS:"Product add successfully",
    CATEGORY_ADD_SUCCESS:"Category add successfully",
    CATEGORY_NOT_FOUND:"Category not found !!",
    NO_PRODUCTS_FOUND:"Product is not found !!",
    AUTH_ERROR: "Auth-Error!",
}

export default message